import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Laravel Casus',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-zinc-900 dark:bg-zinc-900 dark:text-zinc-100 min-h-screen`}
      >
        <nav className='flex items-center justify-between px-8 py-4 border-b border-zinc-200 bg-white dark:bg-zinc-950 dark:border-zinc-800 mb-8'>
          <div className='font-bold text-xl tracking-tight'>Laravel Casus</div>
          <div className='flex gap-6'>
            <Link
              href='/'
              className='no-underline text-zinc-900 dark:text-zinc-100 hover:text-blue-600 dark:hover:text-blue-400 transition-colors'
            >
              Home
            </Link>
            <Link
              href='/#'
              className='no-underline text-zinc-900 dark:text-zinc-100 hover:text-blue-600 dark:hover:text-blue-400 transition-colors'
            >
              temp
            </Link>
            <Link
              href='/#'
              className='no-underline text-zinc-900 dark:text-zinc-100 hover:text-blue-600 dark:hover:text-blue-400 transition-colors'
            >
              temp
            </Link>
            <Link
              href='/usermanagement'
              className='no-underline text-zinc-900 dark:text-zinc-100 hover:text-blue-600 dark:hover:text-blue-400 transition-colors'
            >
              User Management
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
